import pyautogui
import time
pyautogui.press('Win')
pyautogui.write('Notepad')
pyautogui.press('enter')
time.sleep(1)
pyautogui.write('Hi')
pyautogui.press('enter')
time.sleep(1)
pyautogui.press('enter')
pyautogui.write('Well')
pyautogui.write('.')
pyautogui.write('.')
pyautogui.write('.')
time.sleep(1)
pyautogui.write('I am not')
time.sleep(0.5)
pyautogui.write('not really a trojan')
pyautogui.press('enter')
pyautogui.press('enter')
time.sleep(2)
pyautogui.write('Not that Im not scary')
pyautogui.press('enter')
pyautogui.press('enter')
time.sleep(2)
pyautogui.write("well...Dont touch anything ye know")
time.sleep(1)
pyautogui.press('enter')
pyautogui.press('enter')
pyautogui.write("Look at this")
pyautogui.press('enter')
time.sleep(2)
pyautogui.moveTo(1701,322)
time.sleep(2)
pyautogui.write("Look at your mouse pointer")
time.sleep(2)
pyautogui.moveTo(1701,322)
pyautogui.moveTo(300,100)
pyautogui.moveTo(700,250)
pyautogui.moveTo(471,300)
time.sleep(1)
pyautogui.moveTo(151,30)
time.sleep(1)
pyautogui.moveTo(471,000)
time.sleep(1)
pyautogui.moveTo(71,000)
pyautogui.press('enter')
pyautogui.press('enter')
time.sleep(2)
pyautogui.write('funny innit how a simple python code is doing these...')
pyautogui.press('enter')
pyautogui.press('enter')
time.sleep(2)
pyautogui.write('Never execute any file or document unless authorized and the host themselves openening it in their system in front of you')
pyautogui.press('enter')
pyautogui.press('enter')
time.sleep(2)
pyautogui.write('I was designed my Rownak Rajbhar to make people aware of cyber attacks and how easy it is, if my simple code can do all these then think what a professional can make...')
pyautogui.press('enter')
pyautogui.press('enter')
time.sleep(5)
pyautogui.write('I wasnt designed to harm anyone')
pyautogui.write('.')
pyautogui.write('.')
pyautogui.write('.')
pyautogui.press('enter')
pyautogui.press('enter')
time.sleep(2)
pyautogui.write('Or was I?')
pyautogui.hotkey('win','x')
pyautogui.press('u')
pyautogui.press('u')